language: python
python:
  - 2.7
install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap-buildout.py -c travis.cfg
  - bin/buildout -Nq -t 3 -c travis.cfg
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install -q coveralls
  - coveralls

notifications:
  email:
    - gil.cano@gmail.com
    - adriana.rv@gmail.com
    - monica.lenero@gmail.com
